### PR TITLE
Fixes #125 and adds test for iconUrl

### LINKED ISSUE #125: Gulliver fails to fetch Icon from terra.com.br
Gulliver is failing to fetch the icon and displaying a broken image:

`https://www.terra.com.br/manifest-br.json`

### PR DESCRIPTION
**Pull request by juliantoledo**
Fixes #125 and adds test for iconUrl

### CODE REVIEW

**Comment by juliantoledo** [comment]
@andreban @ithinkihaveacat PTAL

File: lib/data-fetcher.js [hunk 1]
```diff
@@ -33,16 +36,58 @@ exports.fetchMetadataDescription = function(url) {
...
+}
+
+function fetchWithUA(url) {
+  const options = {
+    method: 'GET',
+    headers: {
+      'user-agent': USER_AGENT
+    }
+  };
+  return new Promise((resolve, reject) => {
```
Comment (ithinkihaveacat) [inline lib/data-fetcher.js]: I think this should be just `return fetch(url, options);`.

Comment (juliantoledo) [inline lib/data-fetcher.js]: @ithinkihaveacat of course, good catch.

File: lib/pwa.js [hunk 2]
```diff
@@ -150,23 +151,27 @@ function updateMetadataDescription(pwa) {
   });
 }
 
-function updateIcon(pwa, manifest) {
+exports.updateIcon = function(pwa, manifest) {
   const url = manifest.getBestIconUrl();
-  const extension = url.substring(url.lastIndexOf('.'), url.length);
+  const extension = url.substring(url.lastIndexOf('.'), url.length).split('?')[0];
```
Comment (ithinkihaveacat) [inline lib/pwa.js]: This can also be done using node modules via something like `path.extname(url.parse(manifest.getBestIconUrl()).pathname)`. (Slightly more semantic though `path` and `url` need to be imported.)

**Comment by juliantoledo** [comment]
@ithinkihaveacat 
`  const extension = path.extname(url.parse(bestIconUrl).pathname);`
works great, thanks!

File: lib/data-fetcher.js [hunk 3]
```diff
@@ -33,16 +36,50 @@ exports.fetchMetadataDescription = function(url) {
...
       .then(response => {
         resolve(response.json());
       })
       .catch(err => {
         reject(err);
       });
   });
+}
+
+function fetchWithUA(url) {
```
Comment (ithinkihaveacat) [inline lib/data-fetcher.js]: Can we get jsdoc these functions?

Comment (juliantoledo) [inline lib/data-fetcher.js]: @ithinkihaveacat Yes, let me add those here. 
I had another PR for the JSDocs, but I will add another commit here.

**Comment by juliantoledo** [comment]
@ithinkihaveacat I moved the jsdocs from the other PR here.

**Comment by juliantoledo** [comment]
@ithinkihaveacat @andreban ping
